### ISSUE TITLE
Low latency sample manifest not working

### ISSUE THREAD

**Issue by michellezhuogg** [Dash-Industry-Forum/dash-live-source-simulator#101]
The sample manifest on the low latency demo page seems unreachable.
https://reference.dashif.org/dash.js/latest/samples/low-latency/index.html

**Comment by dsilhavy** [comment]
Adressed here: https://github.com/Dash-Industry-Forum/dash.js/pull/3357
Moved to new url: https://livesim.dashif.org/livesim-chunked/chunkdur_1/ato_7/testpic4_8s/Manifest300.mpd

**Comment by TobbeEdgeware** [comment]
Yes. One can also drop the "-chunked" part in the URL, since the two servers have now been merged into one.
@dsilhavy Will you also change the example in the reference page above?

**Comment by dsilhavy** [comment]
@TobbeEdgeware I changed the urls in the player and removed "-chunked" . The sample url above will be updated when a new version is released. The nightly branch is automatically updated after each commit: http://reference.dashif.org/dash.js/nightly/samples/low-latency/index.html

**Comment by tobbee** [comment]
I just checked https://reference.dashif.org/dash.js/nightly/samples/low-latency/index.html and it is working.
