### ISSUE TITLE
dashlivesim.vodanalyzer.dashanalyzer

### ISSUE THREAD

**Issue by janhenhan** [Dash-Industry-Forum/dash-live-source-simulator#102]
Hi,

I'm experimenting with the live simulator and my own content and am a little stuck, so I hope you might be able to help! 

While an older Docker Image I had lying around from around a year ago with the source simulator from back then works without problems, I wanted to upgrade to the newest version from here. When I try to run dashlivesim.vodanalyzer.dashanalyzer e.g. on the testpic_2s manifest to create a config I run into a couple of errors. Could this be related to some changes from Python 2 to 3?
Is the Dash-Live-Source-Simulator now completely based on Python 3? I found mixed info in /setup/instalation.mdown vs the wiki.

  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/mod_wsgi/dashlivesim/vodanalyzer/dashanalyzer.py", line 39, in <module>
    from dashlivesim.dashlib import initsegmentfilter, mediasegmentfilter
  File "/usr/local/bin/mod_wsgi/dashlivesim/dashlib/mediasegmentfilter.py", line 37, in <module>
    from dashlivesim.dashlib.ttml_timing_offset import adjust_ttml_content
  File "/usr/local/bin/mod_wsgi/dashlivesim/dashlib/ttml_timing_offset.py", line 35
    TIME_PATTERN_S = re.compile(rb'(?P<attr>(begin|end))="(?P<hours>\d\d):(?P<minutes>\d\d):(?P<seconds>\d\d)')
                                                                                                                                                                                                      ^
SyntaxError: invalid syntax

Before I also had it asking for the configparser module?!

Hopefully this makes more sense to you than it does to me. 

Best,
Jan

**Comment by TobbeEdgeware** [comment]
All code should now be Python3 which distinguishes "bytes" from "strings", while Python does not. This is the cause of the error message (there is a b in ...re.compile(r**b**'(?P...) . You should now use Python 3.6 or later to run the simulator. Where in the documentation/setup does it mention that Python 2 should be used? I'd like to correct that.

**Comment by janhenhan** [comment]
Hi! Thanks for the quick reply! You'll find mentions of python2 at https://github.com/Dash-Industry-Forum/dash-live-source-simulator/wiki/Installation in the Requirements section. Also dash-live-source-simulator/tools/run_vodanalyzer.sh will still run the dashanalyzer with python instead of python3.
If I run the dashanalyzer with python 3 now, I get a new error message:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/mod_wsgi/dashlivesim/vodanalyzer/dashanalyzer.py", line 40, in <module>
    from mpdprocessor import MpdProcessor
ModuleNotFoundError: No module named 'mpdprocessor'

Not quite sure why, dash live simulator should be in my pythonpath and I didn't seem to have these issues with python2
Any further ideas?

Thanks

**Comment by TobbeEdgeware** [comment]
Thanks for the pointer to the wiki, I will update it.
Regarding your problem with dashanalyzer, that is just a matter of dashlivesim not being in your Python path.
If you go to the vodanalyzer directory and write

      PYTHONPATH=../.. python3 dashanalyzer.py

it will run.
