### ISSUE TITLE
Invalid `trex` atom in ttml subtitles on https://livesim.dashif.org

### ISSUE THREAD

**Issue by vglavnyy** [Dash-Industry-Forum/dash-live-source-simulator#103]
This mp4-ttml stream has an invalid `trex` atom:
https://livesim.dashif.org/dash/vod/testpic_2s/sub_eng/init.mp4

Inside `/moov/mvex/trex` the field track_id **set to 1**.
While inside `/moov/trak/tkhd` the fiekd track_id set to 3.
All fragment (moof) files (https://livesim.dashif.org/dash/vod/testpic_2s/sub_eng/1.m4s) have `/moof/traf/tfhd` with `track_id` set to 3.

This `trex` atom doesn't meet ISO/IEC 14496-12
>8.8.3.1
>Track Extends Box
> Box Type: ‘trex’
> Container: Movie Extends Box (‘mvex’)
> Mandatory: Yes
> Quantity: Exactly one for each track in the Movie Box
> ...
> 8.8.3.3
> track_id identifies the track; this **shall be the track ID** of a track **in the Movie Box**

There is no one track with id=1 inside the `init.mp4` file.
Probably all other `mp4-ttml` streams in https://livesim.dashif.org/dash/vod/testpic_2s also have invalid `trex`.

**Comment by TobbeEdgeware** [comment]
OK. Thanks for pointing this out. It was the same issue in 5 entries and all are fixed now.
