### ISSUE TITLE
<EventStream> element cannot contain @messageData attribute

### ISSUE THREAD

**Issue by paulhiggs** [Dash-Industry-Forum/dash-live-source-simulator#105]
Livesim creates `<EventStream messageData="https://livesim.dashif.org/livesim/mpdcallback/" schemeIdUri="urn:mpeg:dash:event:callback:2015" value="1" />` elements within the `<Period>` but `@messageData` is only permitted in `<Event>`
````
mpdprocessor.py:307
        def create_inline_mpdcallback_elem(BaseURLSegmented):
            "Create an EventStream element for MPD Callback."
            return self.create_descriptor_elem("EventStream", "urn:mpeg:dash:event:callback:2015", value=str(1),
                                               elem_id=None, messageData=BaseURLSegmented)
````

**Comment by TobbeEdgeware** [comment]
OK. This goes back 5 years to https://github.com/Dash-Industry-Forum/dash-live-source-simulator/pull/39
How do you suggest this should be improved?

**Comment by paulhiggs** [comment]
Forgot to mention that this is seen when checking `https://livesim.dashif.org/livesim/periods_60/mpdcallback_30/testpic_2s/Manifest.mpd` against the MPEG DASH 5th Edition schema.

**Comment by paulhiggs** [comment]
> OK. This goes back 5 years to #39
> How do you suggest this should be improved?

In this case, the <EventStream> and <Event> elements should be according to ISO/IEC 23009-1 clause 5.10.4.5.3

**Comment by paulhiggs** [comment]
Based on MPEG DASH 5th edition FDIS clause 5.10.4.5.3, this `<EventStream messageData="https://livesim.dashif.org/livesim/mpdcallback/" schemeIdUri="urn:mpeg:dash:event:callback:2015" value="1" />` should probably be
````
<EventStream schemeIdUri="urn:mpeg:dash:event:callback:2015" value="1">
  <Event messageData="https://livesim.dashif.org/livesim/mpdcallback/"/>
</EventStream>
````

**Comment by TobbeEdgeware** [comment]
OK. Thanks. I'll try to update the code

**Comment by tobbee** [comment]
There is finally a new version 2.0.2 deployed in AWS. It should give the right response:

<EventStream schemeIdUri="urn:mpeg:dash:event:callback:2015" value="1"><Event messageData="https://livesim.dashif.org/livesim/mpdcallback/" /></EventStream>

Sorry for the extremely long time it took to do this simple change.
