### ISSUE TITLE
Malformed content for IMSC1 subtitles with images

### ISSUE THREAD

**Issue by lultimouomo** [Dash-Industry-Forum/dash-live-source-simulator#106]
I'm not sure if this is the proper place to report malformed content on the public simulator instance, but https://livesim.dashif.org/dash/vod/testpic_2s/imsc1_img_swe/init.cmft (referenced from https://livesim.dashif.org/dash/vod/testpic_2s/imsc1_img.mpd ) appears to be malformed. Box `stpp`, sized 205 bytes, contains a child box `mime`, sized 504, which should actually be sized 54.

**Comment by TobbeEdgeware** [comment]
Yes, that is a bug in the content as you point out. It is the same issue with the corresponding imsc1_img_eng/init.cmft file as well.

I've changed the files now, so they should be OK.
