### ISSUE TITLE
Test Asset for MPD Callback event is missing Event element on DASH IF portal

### ISSUE THREAD

**Issue by Gheri** [Dash-Industry-Forum/dash-live-source-simulator#109]
The Test Asset on Dash If portal https://livesim.dashif.org/livesim/periods_60/mpdcallback_30/testpic_2s/Manifest.mpd is missing Event element inside EventStream for DASH callback event "urn:mpeg💨event:callback:2015" and hence not calling callback event on Dash.js Player.
Dash.js Player version is 4.4.1.

Can you please update the Test Asset for the same ??

**Comment by TobbeEdgeware** [comment]
This looks like the same as #105, which I should have fixed almost a year ago. Will make a fix now.

**Comment by tobbee** [comment]
There is now a new version 2.0.2 deployed in AWS. It should give the right response:

`<EventStream schemeIdUri="urn:mpeg:dash:event:callback:2015" value="1"><Event messageData="https://livesim.dashif.org/livesim/mpdcallback/" /></EventStream>`
