### ISSUE TITLE
cc_inserter lacks the proper addition of the ATSC1data marker_bits

### ISSUE THREAD

**Issue by enen92** [Dash-Industry-Forum/dash-live-source-simulator#115]
Dear all,

[In Guidelines for Implementation: DASH-IF Interoperability Points v3.1 ](https://dashif.org/docs/DASH-IF-IOP-v3.1.pdf) the following is stated regarding CEA-608/708 in SEI messages:

- user_structure() – This is a variable length data structure ATSC1_data() defined in section 8.2 of ANSI/SCTE 128 2013-a. 

The description is shown below:

<img width="553" alt="image" src="https://user-images.githubusercontent.com/7375276/211157321-d8b3048a-81f0-4efb-aeb0-296858f48b40.png">

Unfortunately since https://github.com/Dash-Industry-Forum/dash-live-source-simulator/commit/23cb15c35656a731d9f6d78a30f2713eff2ec20d#diff-3372455acaff98fed2743e2f609a073a02d36e8edc38bc43adbebc56a03dfef5R83 the  cc_data is immediately followed by the `rbsp_trailing_bits` (the marker_bits (0xFF) might have been unintentionally removed).
Considering the example of the last cc_data packet in one of the SEI elements:

<img width="1372" alt="image" src="https://user-images.githubusercontent.com/7375276/211157984-02c7f933-228a-4086-bf4f-d826cffe6d7d.png">

Correct sequence should be 0xFC 0x94 0x2F **0xFF** 0x80 and not 0xFC 0x94 0x2F 0x80

I've found this while investigating why FFMpeg couldn't extract the CC caption data of the samples provided by the test server on AWS (namely https://livesim.dashif.org/dash/vod/testpic_2s/cea608.mpd). This is not the sole reason for the lack of interoperability but at least seems to be the only issue out of the scope of FFmpeg.

It'd be great if this could be fixed and the public (affected) samples regenerated.

cc @tobbee

**Comment by tobbee** [comment]
Thanks for the report and for investigating the issues. It seems indeed that I added the rbsp_trailing bits, but dropped the marker_bits at the same time. I agree that the SEI NAL units  still come after the video NALUs. Will try to fix that.

**Comment by tobbee** [comment]
This issue should now have been properly fixed and the assets updated.
The updated content has one line in italics, so it can be distinguished from the earlier version:

https://livesim.dashif.org/livesim/testpic_2s/cea608.mpd
https://livesim.dashif.org/dash/vod/testpic_2s/cea608.mpd

The relevant PRs are:
* #116 
* https://github.com/Dash-Industry-Forum/media-tools/pull/12

Please report back if everything looks OK or not?

**Comment by enen92** [comment]
Thanks a lot @tobbee I can confirm it works now just fine in mpv/ffmpeg
