### ISSUE TITLE
Timestamp problems video vs audio

### ISSUE THREAD

**Issue by bbcrddave** [Dash-Industry-Forum/dash-live-source-simulator#13]
Playing http://vm2.dashif.org/livesim/testpic_6s/Manifest.mpd on Firefox highlights an issue with timestamps generated for the audio streams.

Looking at the media segments, the baseMediaDecodeTimes on the audio stream for the same segment number are exactly 1.875 (=== 90000/48000) multiples of the video. Is the VOD -> live timestamp conversion for audio using the wrong timescale for audio or something?

A similar issue was noted https://github.com/Dash-Industry-Forum/dash.js/issues/649#issuecomment-123609307

Chrome doesn't seem to care and does its best to play anyway

**Comment by TobbeMobiTV** [comment]
@bbcrddave I don't understand the issue. The media clock frequencies for audio and video are 48000 and 90000 as defined in the moov.mdia.mdhd boxes of the init segments (A48/init.mp4 and V300/init.mp4).

Checking the basmeMediaDecodeTime in a segment 240731341.m4s for audio and video, the values are very close up to a factor of 48000/90000 as they should be.

The baseMediaDecodeTime*clock_frequency value should be close to segmentNr*6 which they also are.

Chrome uses these values, so I also don't understand that Chrome doesn't seem to care.

**Comment by TobbeMobiTV** [comment]
@bbcrddave  I've now traced down the issue to Firefox not being able to handle (large?) 64-bitd tfdt baseMediaDecodeTime values. If you try to stream the variant with much more recent availabilityStartTime and 32-bit values: http://vm2.dashif.org/livesim/tfdt_32/testpic_2s/Manifest.mpd 
Firefox 43a2 plays it.

Btw, Chrome had a similar problem a long time ago.

**Comment by bbcrddave** [comment]
Yes, you're right: https://bugzilla.mozilla.org/show_bug.cgi?id=1207478.

Embarrassingly I already knew of that as I reported it :blush:, but I thought it had been fixed in 41. >=FF42 should play this stream fine.

Closing this non-issue, sorry.

**Comment by TobbeMobiTV** [comment]
OK. I was about to file a bug in FF, but I found out that it worked also with 64-bit in FF43a2.

**Comment by jyavenard** [comment]
This is fixed in 42 beta.
Was too late for 41.

**Comment by bbcrddave** [comment]
Thanks Jean-Yves.
