### ISSUE TITLE
Tracks are disabled

### ISSUE THREAD

**Issue by jeanlf** [Dash-Industry-Forum/dash-live-source-simulator#3]
Track header flags in initialization segment indicate that the track is disabled, which should not be the case (disabled tracks should be ignored during presentation). Is there any reason for this ?

jean.

**Comment by TobbeMobiTV** [comment]
Thanks for the note. 

The live simulator itself does take these things directly from the source content which is in http://vm2.dashif.org/dash/vod/testpic_2s/
so it seems to be an issue with our in-house segmenter which was used to prepare the content.

I've manually changed the init.mp4 segments for testpic_2s. Will fix the testpic_6s as well.
