### ISSUE TITLE
MPD timescale not considered for vod analysis

### ISSUE THREAD

**Issue by zangue** [Dash-Industry-Forum/dash-live-source-simulator#36]
The VoD analyzer uses segment duration from MPD and assumes it to be in seconds without considering the timescale value. This means e.g. for VoD MPD with @duration = 2000 and @timescale = 1000 the analyzer will set a duration of 2000 seconds for a segment. Leading to analysis failure due to drift detection in segment duration that actually aren't there.

Instead the analyzer should derivate the segment duration value in seconds using the timescale value, i.e @duration / @timescale

**Comment by TobbeEdgeware** [comment]
This is definitely a limitation. However, a more severe underlying limitation is that only segment durations of full seconds are supported in the calculations, so there is not much gain by having a different timescale than seconds in the manifest for specifying the duration.
