### ISSUE TITLE
H.265/HEVC support

### ISSUE THREAD

**Issue by QueOh** [Dash-Industry-Forum/dash-live-source-simulator#38]
Hi, I tried to test my video encoded with H.265/HEVC codec. It was okay to stream as a VOD streaming service, but it failed when I tried it through dash-live-source-simulator.

> videoCodec (video/mp4;codecs="hvc1.1.6.L93.90") is not supported. 

 According to 'the Guidelines for Implementation', DASH supports both H.264/AVC and H.265/HEVC. So, my question is, does 'Dash-live-source-simulator' supports H.265/HEVC codec for live streaming service?, if not, how can I simulate the DASH live streaming service for UHD video? 

Thanks.

**Comment by TobbeEdgeware** [comment]
Sorry for the late answer. I don't think there is anything in the live source simulator that cares about the actual codec being used. All manipulations are done in the timestamps and sequence numbers of the segments. The lives source simulator only supports content in DASH live profile. Was your VOD asset in that profile and what player did you use?
