### ISSUE TITLE
Accept sub-second segment durations in config files

### ISSUE THREAD

**Issue by rodrigobdz** [Dash-Industry-Forum/dash-live-source-simulator#41]
DLS accepts only `int` values as segment duration in config files. For segment durations under a second an error is thrown. It should accept sub-second segment durations as well.

This line defines the segment duration in config files as int:
https://github.com/Dash-Industry-Forum/dash-live-source-simulator/blob/30639d2798f7f60707b9097ef1b4ac79cbc94e2e/dashlivesim/dashlib/configprocessor.py#L225

**Comment by TobbeEdgeware** [comment]
The live-source simulator is pretty tied to using an integral number of seconds in its calculations, and assumes to be able to do exact wrap-around calculations, to be able to sync with wall-clock. One could introduce timescale and use rational durations smaller than a second like 1/2s, but float is too general.

Still, introducing rational segment durations, would need changes to the code in quite a number of places. Do you have a test sequence that could be use to try this out?

**Comment by rodrigobdz** [comment]
Sure. I will host the files on my google drive for you to download them. Please notify me when you have downloaded them already.

https://drive.google.com/open?id=0Bxi4TVQO8FJuQVp2d0tEaE1yNGs

**Comment by TobbeEdgeware** [comment]
I got the files. 750ms segment duration. Thanks.

**Comment by rodrigobdz** [comment]
You're welcome

**Comment by tobbee** [comment]
This will need to happen in a complete rewrite of the tool in Go. It is too hard to fit it into the current structure.
