### ISSUE TITLE
A question on the format of minimumUpdatePeriod

### ISSUE THREAD

**Issue by dahee1jeong** [Dash-Industry-Forum/dash-live-source-simulator#43]
Hi,
Some contents provided by Dash-Industry-Forum show the format of minimumUpdatePeriod like below.

The contents are in the following links. 
•http://vm2.dashif.org/livesim/testpic_2s/Manifest.mpd
•http://vm2.dashif.org/livesim-dev/testpic_2s/Manifest.mpd

And if you open the mpd files, you can see that minimumUpdatePeriod are written like below.
**minimumUpdatePeriod="P100Y"**

As I know, it's usually represented "**PT**100Y", including 'T', which means presented timestamp.
However, it doesn't include 'T' . 
I'm wondering if this is written in Dash specification. Can you share the document if you have?

**Comment by bbcrddave** [comment]
The [DASH schema](http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd) specifies `minimumUpdatePeriod` as type `xs:duration`

You can read all about that exact definition of that type in the [XML Schema Definition Language](https://www.w3.org/TR/xmlschema11-2/#duration) spec, but the basic answer is that the `T` indicates the start of the time (hours, minutes, seconds) section and so it would be incorrect to include as you suggest in your example.

**Comment by TobbeEdgeware** [comment]
Yes, there are different formats for xs:duration and xs:dateTime.
I close this issue.
