### ISSUE TITLE
Set cache control headers on time sync URL

### ISSUE THREAD

**Issue by TheModMaker** [Dash-Industry-Forum/dash-live-source-simulator#45]
The time sync URL (e.g. `http://vm2.dashif.org/dash/time.txt`) is used for determining clock sync. The clients should send a HEAD request to get the Date header from the response. Unfortunately the response does not include cache control headers, meaning the response may be cached. Firefox will cache the entire HEAD response, not sending it at all.

The minimum would be to set `Cache-control: no-cache` to ensure the HEAD is at least sent again. Setting `Cache-control: no-cache, no-store` would mean it cannot be cached at all.

Originally filed in google/shaka-player#606

**Comment by TobbeEdgeware** [comment]
Good point. I've changed the Apache config to set the headers to `Cache-control: no-cache, no-store` for that specific file.
