### ISSUE TITLE
Scaling presentationTimeOffset by timescale

### ISSUE THREAD

**Issue by PaulRutland** [Dash-Industry-Forum/dash-live-source-simulator#46]
When using multiple periods, each period has a presentationTimeOffset attribute added to the SegmentTemplate.
This value should be scaled by the SegmentTemplate timescale, if present.
DASH specification says: 

> presentationTimeOffset : The value of the presentation time offset in seconds is the division of the value of this attribute and the value of the timescale attribute.

If you enable segment timeline output the problem is clear, audio and video adaptation sets get different timescales but use the same presentationTimeOffset value.
eg http://vm2.dashif.org/livesim-dev/segtimeline_1/periods_4/testpic_6s/Manifest.mpd

When not using segment timeline the timescale defaults to 1 and the presentationTimeOffset used is the same as the period start time.

I think the mpdprocessor needs to rescale the presentationTimeOffset when it sets the segment template timescale?

**Comment by TobbeEdgeware** [comment]
You're right. Looks like a bug.

**Comment by TobbeEdgeware** [comment]
Sorry for the extremely slow response. Thanks for the report and the PR to fix it.
