### ISSUE TITLE
All samples signalled as sync

### ISSUE THREAD

**Issue by LloydW93** [Dash-Industry-Forum/dash-live-source-simulator#48]
Only keyframes should be marked as is_sync in the mp4, however they all appear to be, at least in http://vm2.dashif.org/livesim/testpic_6s/Manifest.mpd. This causes decoding artefacts on ABR and seek.

(Originally from https://github.com/Dash-Industry-Forum/dash.js/issues/1786)

**Comment by TobbeEdgeware** [comment]
OK. I agree that the content does not have the sample_is_non_sync_sample bit set in the trun box. This is straight from the encoder, and is quite common. However, key-frames are actually signaled in the 2-bit sample-depends-on flag, which have value 2 for I frames and 1 for the others as in Section 8.6.4.3 of of the file format spec ISO/IEC 14496-12. Anyway, I will make a small script to go through the flags of the samples in the trun box and set it.

**Comment by TobbeEdgeware** [comment]
Sorry for the long delay, but I've fixed the sample flags now. I made a simple tool for fixing them at https://github.com/Dash-Industry-Forum/media-tools/blob/master/python/dash/segment_modifiers/fix_sync_sample_flags.py

IDR-frames are now signaled with `depends_on == 2` and `sample_is_not_sync_sample == 0` while all other frames are signaled with `depends_on == 1` and `sample_is_not_sync_sample == 1`.
