### ISSUE TITLE
Support for non-zero startNumber

### ISSUE THREAD

**Issue by TobbeMobiTV** [Dash-Industry-Forum/dash-live-source-simulator#5]
One test case for live is to have no startNumber attribute in the MPD. This corresponds to the default value of 1.

To handle this and other cases, it is suggested to add another URI parameter to start at any startNumber. For example, sn_X, if X = 1, there should be no startNumber in the Manifest.

**Comment by wilaw** [comment]
How would you signal a startNumber that starts at 1 then?

Suggest sn=-1 to signal no startNumber attribute.

sn query arg omitted => uses default startNumber=1
sn=-1, startNumber omitted from manifest
sn=0..n, startNumber used as described

-Will

**Comment by TobbeMobiTV** [comment]
I've added this functionality including the -1 option in commit 5227683.
The option is called snr_X and all timing in the segments is changed so playback with snr_1000 or something like that shall be synchronized with default, although there is 1000 difference in segment number. Will make this part of release 1.1, that will come any minute.

**Comment by TobbeMobiTV** [comment]
It is now on the vm2 dev server, like: 
http://vm2.dashif.org/livesim-dev/snr_200/testpic_2s/Manifest.mpd
http://vm2.dashif.org/livesim-dev/snr_-1/testpic_2s/Manifest.mpd
http://vm2.dashif.org/livesim-dev/snr_1/testpic_2s/Manifest.mpd
