### ISSUE TITLE
Audio chunks time misalignment

### ISSUE THREAD

**Issue by epiclabsDASH** [Dash-Industry-Forum/dash-live-source-simulator#56]
While testing a SegmentTimeline based stream generated by livesim (https://vm2.dashif.org/livesim-dev/segtimeline_1/testpic_2s/Manifest.mpd) I have noticed there is a time misalignment in audio chunks. 

More specifically, start times declared in the mpd, and used to name the segments, are around 2 seconds behind the real pts within the segments.

**Comment by TobbeEdgeware** [comment]
I don't see such big differences, but only tfdt.baseMediaDecodeTime being 1024 or 2048 ticks bigger than the name.

**Comment by epiclabsDASH** [comment]
Let me re-take a look to this and get back to you with more info. Thanks.

**Comment by TobbeEdgeware** [comment]
@epiclabsDASH There was an error in the metadata generation so the segment duration was off by one entry (typically 1024 samples). However, with repeat-count this could be amplified a number of times. This should now be fixed for https://vm2.dashif.org/livesim-dev/segtimeline_1/testpic_2s/Manifest.mpd with updated metadata.
