### ISSUE TITLE
SCTE35 InbandEventStream has no @value attribute

### ISSUE THREAD

**Issue by bbcrddave** [Dash-Industry-Forum/dash-live-source-simulator#6]
SCTE 67 2014, 12.1.5.4 describes the signalling of inband SCTE35 events in the MPD. It states that "the value attribute should match the PID value of the original SCTE 35 messages". 

Whilst technically `@value` is optional, the owner of the schemeIdUri has defined its meaning and therefore I think it is required in this case.

emsg.value is non-null ("1001") - this should be the value of `@value`.

I expect implementations will match schemeIdUri/value pairs defined in the MPD and emsg boxes and would fail to associate the emsg with any event stream and discard the message.

**Comment by TobbeMobiTV** [comment]
I've followed the DASH-IF ad insertion guidelines (now included in DASH-IF IOP 3.0), which didn't have a value specified, but I see no problem of adding the value in the <EventStrem> element. 

What about the schemeIdUri? 

The SCTE document says `urn:scte:scte35:2013a:xml` while DASH-IF IOP says `urn:scte:scte35:2013:xml`.

Should the livesimulator and the DASH-IF IOP guidelines be updated?

**Comment by bbcrddave** [comment]
The example in the DASH-IF IOP only appears to show a MPD EventStream?

I just noticed that the IOP states that SCTE35 inband event carriage is defined by SCTE DVS 1208 to which I do not have access, so perhaps the correct behaviour has changed from SCTE 67. This probably means that the schemeIdUri used is correct, but someone with a copy of the spec would need to confirm.

Either way, I'd be surprised if `@value` is not meant to be specified for InbandEventStream.
