### ISSUE TITLE
Thumbnail test vector -Conformance issue

### ISSUE THREAD

**Issue by niteeshbhat** [Dash-Industry-Forum/dash-live-source-simulator#61]
http://vm2.dashif.org/livesim-dev/testpic_2s/Manifest_thumbs.mpd.

This vector fails conformance test with error report as

Line:Col[44:76]:cvc-datatype-valid.1.2.1: 'thumbs' is not a valid value for 'integer'.
Line:Col[44:76]:cvc-attribute.3: The value 'thumbs' of attribute 'id' on element 'AdaptationSet' is not valid with respect to its type, 'unsignedInt'.
Unexpected error: For input string: "thumbs"
MPD validation not successful - DASH is not valid!

It turns out from DASH schema that AdaptationSet @id should be unsignedInt .. but here its string. 

Also EssentialProperty schemeIdUri for thumbnail should be 'http://dashif.org/guidelines/thumbnail_tile'

**Comment by TobbeEdgeware** [comment]
Sorry for not following this stream if issues. I've finally removed the id on the Adaptation-set and corrected the EssentialProperty
