### ISSUE TITLE
Test URL not working

### ISSUE THREAD

**Issue by ankitg12** [Dash-Industry-Forum/dash-live-source-simulator#62]
The testurl "http://vm2.dashif.org/livesim/testpic_2s/two_regions.mpd"  mentioned in https://github.com/Dash-Industry-Forum/dash-live-source-simulator/wiki/Test-URLs is not accessible:

Getting following error for this:
DASH Proxy Error: [Errno 2] No such file or directory: '/var/www/dash-live/content/testpic_2s/two_regions.mpd'
 URL=/livesim/testpic_2s/two_regions.mpd

Can you please correct this.

**Comment by TobbeEdgeware** [comment]
Sorry for very late response. There are two versions of two-region subtitle tests.

- stpp_two_regions.mpd
- stpp_two_regions_multi_color.mpd

I've linked two_regions.mpd to the former
