### ISSUE TITLE
HTTPS variable not passed to mod_wsgi/mod_dashlivesim.py

### ISSUE THREAD

**Issue by forquare** [Dash-Industry-Forum/dash-live-source-simulator#73]
Hi,

My environment:

- CentOS Linux release 7.5.1804 (Core) 
- httpd 2.4.6
- mod_wsgi 3.4
- mod_ssl 2.4.6

I'm seeing issues identical to that of issue #14, where the BaseURL is always http.  Having done some tests the HTTPS environmental doesn't get included in `mod_wsgi/mod_dashlivesim.py`

According to [Graham Dumpleton on Twitter](https://twitter.com/GrahamDumpleton/status/1088716767134916608): 

> The CGI HTTPS variable is deliberately stripped after setting wsgi.url_scheme to make those applications which used HTTPS in a non WSGI conformant way to fix their code. So if the application is using old CGI HTTPS variable the application should be fixed.

After a *very* quick search, I can't see any documentation to back this up, but it certainly confirms what I am seeing.

**Comment by TobbeEdgeware** [comment]
Why does it need to be forwarded? Livesim uses https or http depending on the request schema.

    http://livesim.dashif.org/livesim/testpic_2s/Manifest.mpd

gives

        <BaseURL>http://livesim.dashif.org/livesim/testpic_2s/</BaseURL>

while 

    https://livesim.dashif.org/livesim/testpic_2s/Manifest.mpd

gives

        <BaseURL>https://livesim.dashif.org/livesim/testpic_2s/</BaseURL>

**Comment by Murmur** [comment]
Similar effect but on Nginx module, we updated Livesim today and it always does `Location` http reply redirect to a session specific url identifier, like Wowza dash server is doing?

We request HTTPS manifest but new livesim send location redirect to HTTP address and manifest baseurl is http link. Original protocol is not used for location+baseurl values.

`https://my.test.com/livesim/test1/manifest.mpd`
`Location: http://my.test.com/livesim/sts_1566291740_test1/manifest.mpd`
`<MPD><BaseURL>http://my.test.com/livesim/sts_1566291740_test1/manifest.mpd</BaseURL>...</MPD>`

**Comment by TobbeEdgeware** [comment]
Sorry for not fixing this earlier. It should have been resolved now in version 2.0.1 as part of fixing Issue #97 when I moved livesim to a modern platform and Python3. It was due to different versions of mod_wsgi.
