### ISSUE TITLE
Test URL contains incorrect link

### ISSUE THREAD

**Issue by pmouawad** [Dash-Industry-Forum/dash-live-source-simulator#74]
Hello,
Thanks for this useful repository.

I'd like to report that In:

- https://github.com/Dash-Industry-Forum/dash-live-source-simulator/wiki/Test-URLs

2 examples point to same URL:

- Startover interval form now - 20s to now + 20s. SegmentTimeline
- Startover interval form now - 20s to now + 20s. $Number$ manifest

The URL being:

- https://livesim.dashif.org/livesim/segtimeline_1/startrel_-20/stoprel_20/timeoffset_0/testpic_2s/Manifest.mpd

Regards

**Comment by TobbeEdgeware** [comment]
Thanks for pointing this out. Sorry for delay in fixing it.
