### ISSUE TITLE
There is no @availabilityTimeOffset and @availabilityTimeComplete in the mpd for chunked stream

### ISSUE THREAD

**Issue by junsoopark** [Dash-Industry-Forum/dash-live-source-simulator#75]
Currently there is no @availabilityTimeOffset and @availabilityTimeComplete in the mpd for Low Latency(chunked). But I could see the BaseURL with @availabilityTimeOffset and @availabilityTimeComplete in the mpd until a few days ago.
Is it a bug of the simulator running? Please take a look at this.

**Comment by TobbeEdgeware** [comment]
Chunks are only supported on a branch of the livesim. If you use the URLs

https://livesim.dashif.org/livesim-chunked/chunkdur_1/ato_7/testpic4_8s/Manifest300.mpd

and

https://livesim.dashif.org/livesim-chunked/chunkdur_1/ato_7/testpic4_8s/Manifest.mpd

you should see ATO and ATC.

**Comment by junsoopark** [comment]
Currently the response for the request to those mpd urls does not have ATO and ATC.. What am I doing wrong?

**Comment by TobbeEdgeware** [comment]
This was an error introduced by me when trying to play around with the BaseURL. Should work now again. Sorry for the problem.
