### ISSUE TITLE
Query string not being accpeted

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/dash-live-source-simulator#80]
The URL is throwing errors to the[ cache bypass technique](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest#Bypassing_the_cache) used, e.g. URL: http://livesim.dashif.org/livesim-dev/periods_1/testpic_2s/Manifest.mpd?1560849939915
Response:
Unknown file extension: .mpd?1560849939915

So its taking the benign query string as a part of the URL.

Related issue: https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/issues/447

**Comment by TobbeEdgeware** [comment]
This is not an issue with livesim, but with livesim-dev. The former uses mod_python and the latter mod_wsgi Apache plusgins. Fixed in PR #84.

**Comment by TobbeEdgeware** [comment]
I've updated the livesim-dev instance and it seems to be working fine with query parts now.
