### ISSUE TITLE
saio is not updated to reflect a change in the position of senc

### ISSUE THREAD

**Issue by komar007** [Dash-Industry-Forum/dash-live-source-simulator#82]
If the input segment uses `tfdt` box version 0, when `baseMediaDecodeTime` is modified, `tfdt` may change version to 1 as a result of `baseMediaDecodeTime` growing beyond the limit of 32 bits (see `process_tfdt` in `mediasegmentfilter.py`).
As a result, the size of `tfdt` increases and the offsets stored in `saio` (referencing Sample Auxiliary Information stored inside `saiz`) may no longer be valid, resulting in an inconsistent (broken) file.

See this example input file opened in isoviewer:
![2019-07-18-092513_830x509_scrot](https://user-images.githubusercontent.com/108297/61437652-e7e2a400-a93d-11e9-958c-350febb88122.png)

We can see how the one offset in `saio` equals 721. When `mediasegmentfilter.py` increases the size of `tfdt` (which in this file is version 0), `senc` will move and the offset will not longer be valid.

Since dash-live-source-simulator modifies the size of boxes while rewriting them, there may be more such internal references that need fixing.

**Comment by TobbeEdgeware** [comment]
OK. Thanks for the report. I'll look into it.

**Comment by TobbeEdgeware** [comment]
Fixed in PR #83.
