### ISSUE TITLE
Check audio code for English language

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/dash-live-source-simulator#87]
As reported by a user:

For the following link

        https://livesim.dashif.org/livesim/testpic_2s/Manifest.mpd

The audio code is "eng" although according to RFC 5646 its only "en".

**Comment by TobbeEdgeware** [comment]
Yeah, language codes are a mess. It is not even easy to see in RFC 5646 how to use them.

Anyway, I've changed the asset in the ticket. I'll write a script to go through all other mpd's and change them as well.

**Comment by tobbee** [comment]
It tooks some time, but now the language codes should be two letters everywhere.
