### ISSUE TITLE
SegmentTimeline and wraps

### ISSUE THREAD

**Issue by Intrepd** [Dash-Industry-Forum/dash-live-source-simulator#88]
I think I see an inconsistency when using SegmentTimeline and when the testpic_2s source wraps around.

Although you can wait to request the manifest around the top of each hour, an immediate way to reproduce this seems to be to simulate a manifest pull right before the wrap around using the start_ parameter via:

> START=$(($(date +%s)-3598)); wget -qO - http://livesim.dashif.org/livesim/start_$START/segtimeline_1/testpic_2s/Manifest.mpd

showing a timeline 296640000-323640000:

`<S d="180000" r="150" t="296640000" />`

and right after the wrap via

> START=$(($(date +%s)-3602)); wget -qO - http://livesim.dashif.org/livesim/start_$START/segtimeline_1/testpic_2s/Manifest.mpd`

showing a timeline 297000000-2973600000:

`<S d="180000" t="297000000" />`
`<S d="180000" />`

I think in the above case, the first timeline entry needs a @r of roughly 149, because the previous manifest indicates the timeline ending at 323640000.

**Comment by TobbeEdgeware** [comment]
Uploaded fix on livesim-dev. Will be in next release on master -> livesim
