### ISSUE TITLE
Add segmentTimeline example

### ISSUE THREAD

**Issue by wilaw** [Dash-Industry-Forum/dash-live-source-simulator#9]
All examples use segmentTemplate with $number$ substitution. Since DASH-AVC/264 also support s segmentTimeline addressing, it would be great to have a reference example that used $time$ substitution. Would also be good if example included
1. Segments that varied in duration some amount, with some use of the 'r' parameter 
3.  A DVR window of at least 5min.

**Comment by TobbeMobiTV** [comment]
This is 90% ready in the branch https://github.com/Dash-Industry-Forum/dash-live-source-simulator/tree/feature-segment-timeline. It uses a list of exact durations for all segments. Since the testpic sequence have audio segments with slight variations in the duration it exercises the 'r' parameter. My plan is to have this finished before the end of January.

**Comment by wilaw** [comment]
@Tobbe – this would be great. We need this for the dash.js debug for 2.0 release. We have playback issues with segmentTimeline streams, but people can never leave them up for long enough to enable resolution. The great advantage of live sim is that it is available consistently 24x7.

Please notify IOP list or dash.js list once branch is pulled in and functionality is available online.

Cheers

Will


From: Torbjörn Einarsson
Reply-To: Dash-Industry-Forum/dash-live-source-simulator
Date: Friday, January 15, 2016 at 8:10 AM
To: Dash-Industry-Forum/dash-live-source-simulator
Cc: Will Law
Subject: Re: [dash-live-source-simulator] Add segmentTimeline example (#9)


This is 90% ready in the branch https://github.com/Dash-Industry-Forum/dash-live-source-simulator/tree/feature-segment-timeline<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Dash-2DIndustry-2DForum_dash-2Dlive-2Dsource-2Dsimulator_tree_feature-2Dsegment-2Dtimeline&d=CwMCaQ&c=96ZbZZcaMF4w0F4jpN6LZg&r=KkevKJerDHRF9WRs8nW8Ew&m=hwjm_4G5RetXZUYdQCjiBGic4YRhsNwWZhaeCVXzkTk&s=S3eaIshVgVE2DeFF_IKZ_OUBtCv6X9nq-ARutqwLjXQ&e=>. It uses a list of exact durations for all segments. Since the testpic sequence have audio segments with slight variations in the duration it exercises the 'r' parameter. My plan is to have this finished before the end of January.

**Comment by waqarz** [comment]
@TobbeMobiTV from a DASH-IF test point of view, clients should be tested separately for "r=-1" case, are you also implementing this? If not we can add this.

**Comment by TobbeMobiTV** [comment]
I've made a first version that is available to test at http://vm2.dashif.org/livesim-dev/segtimeline_1/testpic_6s/Manifest.mpd or the corresponding 2s segment.
This is based on initial work form Nomor. The source is in the branch feature-segment-timeline.

The 1.5.1 player starts to play but stops after some time. The 2.0 player didn't even start. Any help with scrutinizing the MPD or other artifacts is appreciated. (The minimumUpdatePeriod=0, btw).

**Comment by waqarz** [comment]
@TobbeMobiTV I see in the MPD minimumUpdatePeriod="0"; it should be minimumUpdatePeriod="PT0S" etc.

**Comment by TobbeMobiTV** [comment]
@waqarz Thanks for pointing it out. I should have tested with the MPD validator. I did that and saw that I needed to add publishTime and id to the MPD, as well.

**Comment by TobbeMobiTV** [comment]
http://vm2.dashif.org/livesim-dev/segtimeline_1/testpic_2s/Manifest.mpd is now updated to produce valid MPDs.

However, I get the same error in reference player 1.5.1:

chunk.bufferedRange is undefined on line 546 in BufferController.js

2.0 fetches some segments, but doesn't start.

**Comment by TobbeMobiTV** [comment]
This works well in 2.0RC4, so I think we can close this now, although some details still can be improved.

**Comment by AkamaiDASH** [comment]
:+1:
