### ISSUE TITLE
CEA-608 stream does not conform to H.264 standards

### ISSUE THREAD

**Issue by ArktekniK** [Dash-Industry-Forum/dash-live-source-simulator#99]
Hello,

https://livesim.dashif.org/dash/vod/testpic_2s/cea608.mpd

This stream is non-conformant to H.264. The stream is also supplied in the DASH.js test player list of available streams. DASH.js seems to be able to play this non-conformant stream without issue. 

The above stream contains two channels of CEA-608 closed caption data which is correctly contained within NAL units of type 0x06 - Supplemental Enhancement Information. However, the **order** of the NALs does not conform to the H.264 specification. 
Specifically, the passage `7.4.1.2.3 Order of NAL units and coded pictures and association to access units`

> The following constraints shall be obeyed by the order of the coded pictures and non-VCL NAL units within an access unit:
> – When an access unit delimiter NAL unit is present, it shall be the first NAL unit. There shall be at most one access unit delimiter NAL unit in any access unit.
> – **When any SEI NAL units are present, they shall precede the primary coded picture.**
> ...

(Emphasis mine)

Please see the first segment analysis screenshot below (Produced from an internal tool).
SEI NAL units number 4 and 5 should come before the primary coded picture, which is NAL number 3. 

![image](https://user-images.githubusercontent.com/9900921/86120751-c6d27f00-bacc-11ea-9502-91294e95162d.png)

As this is the only content available that has multiple CEA-608 channels/languages embedded within the video sream, it would be great to have it resolved.

Thanks!

**Comment by ArktekniK** [comment]
Forgot to mention that additionally, the live version of this stream is also affected in the same way:
https://livesim.dashif.org/livesim/testpic_2s/cea608.mpd

**Comment by TobbeEdgeware** [comment]
Yeah, that is correct. That's a risk of making test assets by hand and also implementing the player ;-)
Nobody has noticed in over 4 years!

It's an old sin in (https://github.com/Dash-Industry-Forum/dash-live-source-simulator/blob/develop/dashlivesim/cc_inserter/cc_inserter.py) which inserts SEI nal units in the video samples.
It inserts them at the end, but putting them at the start after them after any SPS/PPS would be the right thing to do.

I'll look into updating both the code and the asset.

**Comment by ArktekniK** [comment]
That's great, thanks for confirming that.
I did take a look at cc_inserter.py but unfortunately didn't have the time to investigate further and put together a PR.
FYI In my particular case our native player didn't pick up the CCs because of an early-out as soon as the primary encoded picture is found.

**Comment by TobbeEdgeware** [comment]
Should be fixed now. I wrote a small program to move the NAL units to the right position in the samples since I didn't have the original template for generating scc files around. I haven't fixed the cc_inserter.py, so I made #99 for that.

**Comment by TobbeEdgeware** [comment]
Hmm. I also see the message when I run ffprobe, but it is a bit strange since the SEI NAL units of type 4 are 56 bytes long, thus not even close to 424 bytes long.

A typical SEI CEA-608 NAL unit looks like:

660435b500314741393403cefffd9420fd94aefd9162fd73f7fde5bafd91b9fdb0b0fdbab0fdb0bafdb031fdbab0fdb080fd942cfd942fff

**Comment by TobbeEdgeware** [comment]
There were actually two issues with the CEA-608 SEI NAL units in the asset. 

1. They end with an 0xff byte instead of an 0x80 rbsp_trailing_bits byte as it should
2. The payload length included that byte which it shouldn't

 I've fixed these two bytes in each CEA-608 NAL unit in the segments, so now the content should be fine.
 I've also added some SEI NAL unit parsing to the mp4ff open source project, to verify that the NAL units are now fine:
 https://github.com/edgeware/mp4ff/pull/116

**Comment by enen92** [comment]
@TobbeEdgeware @tobbee were the public samples actually fixed? Running mp4ff against an mp4 download of https://livesim.dashif.org/dash/vod/testpic_2s/cea608.mpd still reports the SEI NALUs after the primary coded picture.

<img width="843" alt="image" src="https://user-images.githubusercontent.com/7375276/211163093-1fded160-879c-445f-a949-f1de4ee9c4e3.png">

while a conformant file reports them before:

<img width="854" alt="image" src="https://user-images.githubusercontent.com/7375276/211163222-24db9112-7713-412f-807a-a343d9f1c5d8.png">

Recent ffmpeg versions complain about the "Late SEI" and don't even consider the elements as part of the picture.

Regarding the 0xFF removal of the last comment it was likely the marker_bits...
 I've opened https://github.com/Dash-Industry-Forum/dash-live-source-simulator/issues/115 for that particular issue
